import Head from 'next/head'
import HeroSection from '../components/home/HeroSection'
import PartiesEvents from '../components/home/PartiesEvents'
import FeaturedNews from '../components/home/FeaturedNews'
import TravelFaqs from '../components/home/TravelFaqs'
import HotelBooking from '../components/home/HotelBooking'
import HotelBookingDesktop from '../components/home/HotelBookingDesktop'

export default function Home() {
  return (
    <div>
      <Head>
        <title>TravelGay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <HeroSection />
     <HotelBooking/>
     <HotelBookingDesktop/>
     <PartiesEvents />
     <FeaturedNews />
     <TravelFaqs />
    </div>
  )
}
